# 1


In [3]:
import numpy as np

np.arange(10+1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
2**np.arange(10+1)

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024],
      dtype=int32)

# 2

In [27]:
np.arange(10+1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
2**np.arange(10+1)

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024],
      dtype=int32)

In [7]:
np.arange(10+1)[:, np.newaxis]

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [11]:
np.arange(10+1)* np.arange(10+1)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [26]:
np.arange(10+1)* (2* np.arange(10+1))

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162, 200])

In [12]:
np.arange(10+1)* (2* np.arange(10+1)[:, np.newaxis])

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [  0,  12,  24,  36,  48,  60,  72,  84,  96, 108, 120],
       [  0,  14,  28,  42,  56,  70,  84,  98, 112, 126, 140],
       [  0,  16,  32,  48,  64,  80,  96, 112, 128, 144, 160],
       [  0,  18,  36,  54,  72,  90, 108, 126, 144, 162, 180],
       [  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200]])

In [24]:
S = np.arange(10+1)* np.arange(10+1)[:, np.newaxis]
S = np.triu(S)
S

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  0,   0,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  0,   0,   0,   9,  12,  15,  18,  21,  24,  27,  30],
       [  0,   0,   0,   0,  16,  20,  24,  28,  32,  36,  40],
       [  0,   0,   0,   0,   0,  25,  30,  35,  40,  45,  50],
       [  0,   0,   0,   0,   0,   0,  36,  42,  48,  54,  60],
       [  0,   0,   0,   0,   0,   0,   0,  49,  56,  63,  70],
       [  0,   0,   0,   0,   0,   0,   0,   0,  64,  72,  80],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  81,  90],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 100]])

In [33]:
S[:10+1,10]

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [14]:
np.arange(9, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [18]:
np.arange(-1, 9, 1)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [19]:
np.arange(-1, 9, 2)

array([-1,  1,  3,  5,  7])

In [34]:
S = 1.1**np.arange(5+1) * 0.9**(2*np.arange(5+1)[:, np.newaxis]);
S = np.triu(S)
S

array([[1.        , 1.1       , 1.21      , 1.331     , 1.4641    ,
        1.61051   ],
       [0.        , 0.891     , 0.9801    , 1.07811   , 1.185921  ,
        1.3045131 ],
       [0.        , 0.        , 0.793881  , 0.8732691 , 0.96059601,
        1.05665561],
       [0.        , 0.        , 0.        , 0.70734797, 0.77808277,
        0.85589104],
       [0.        , 0.        , 0.        , 0.        , 0.63024704,
        0.69327175],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.56155011]])

In [35]:
C = np.zeros((5+1, 5+1)) 
# += np.arange(5+1)[:, np.newaxis]
# C[:,-1]
C[:,5] = np.arange(5+1)
C[:4+1, 4]

array([0., 0., 0., 0., 0.])

In [36]:
C[1:4+2, 4+1]

array([1., 2., 3., 4., 5.])

In [37]:
C[:4+1, 4+1]

array([0., 1., 2., 3., 4.])

In [38]:
for j in range(5-1, -1, -1):
    print(j)

4
3
2
1
0


In [39]:
for j in range(5-1, 0, -1):
    print(j)

4
3
2
1
